[04-28 13:11:23]: [INFO] Created column 'regdate' and set the current timestamp, 1588101083642, to all 0 rows
[04-28 13:11:25]: [INFO] SQLite Setup finished
[04-28 13:11:25]: [INFO] Hooked into LuckPerms!
[04-28 13:11:25]: [INFO] Hooked successfully into Essentials
[04-28 13:11:25]: [INFO] Hooked successfully into Multiverse-Core
[04-28 13:11:26]: [INFO] AuthMe 5.6.0-SNAPSHOT build n.2388 successfully enabled!
[04-28 13:11:30]: [INFO] Downloading GEO IP database, because the old database is older than 30 days or doesn't exist
[04-28 13:11:30]: [WARN] No MaxMind credentials found in the configuration file! GeoIp protections will be disabled.
[04-28 13:11:31]: [INFO] There is no newer GEO IP database uploaded to MaxMind. Using the old one for now.
[04-28 13:11:31]: [WARN] Could not download GeoLiteAPI database [FileNotFoundException]: plugins\AuthMe\GeoLite2-Country.mmdb (系统找不到指定的文件。)
[04-28 13:11:31]: java.io.FileNotFoundException: plugins\AuthMe\GeoLite2-Country.mmdb (系统找不到指定的文件。)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(Unknown Source)
	at java.io.RandomAccessFile.<init>(Unknown Source)
	at fr.xephi.authme.libs.com.maxmind.db.BufferHolder.<init>(BufferHolder.java:20)
	at fr.xephi.authme.libs.com.maxmind.db.Reader.<init>(Reader.java:121)
	at fr.xephi.authme.service.GeoIpService.startReading(GeoIpService.java:173)
	at fr.xephi.authme.service.GeoIpService.updateDatabase(GeoIpService.java:144)
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[04-28 13:14:56]: [INFO] AuthMe 5.6.0-SNAPSHOT-b2388 disabled!
[04-28 13:21:24]: [INFO] Connection arguments loaded, Hikari ConnectionPool ready!
[04-28 13:21:26]: [WARN] Can't initialize the MySQL database: [CommunicationsException]: Communications link failure

The last packet successfully received from the server was 12 milliseconds ago.  The last packet sent successfully to the server was 11 milliseconds ago.
[04-28 13:21:26]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 12 milliseconds ago.  The last packet sent successfully to the server was 11 milliseconds ago.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
	at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:201)
	at com.mysql.jdbc.MysqlIO.negotiateSSLConnection(MysqlIO.java:4869)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1656)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1217)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2189)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor95.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:354)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:554)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:167)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:175)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:76)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470)
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384)
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488)
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:895)
	at java.lang.Thread.run(Unknown Source)
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
	at sun.security.ssl.Handshaker.process_record(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:186)
	... 43 more
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
	at com.mysql.jdbc.ExportControlled$X509TrustManagerWrapper.checkServerTrusted(ExportControlled.java:302)
	at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(Unknown Source)
	... 52 more
Caused by: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(Unknown Source)
	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(Unknown Source)
	at java.security.cert.CertPathValidator.validate(Unknown Source)
	at com.mysql.jdbc.ExportControlled$X509TrustManagerWrapper.checkServerTrusted(ExportControlled.java:295)
	... 53 more

[04-28 13:21:26]: [WARN] Please check your database settings in the config.yml file!
[04-28 13:21:26]: [WARN] Could not create data source: [CommunicationsException]: Communications link failure

The last packet successfully received from the server was 12 milliseconds ago.  The last packet sent successfully to the server was 11 milliseconds ago.
[04-28 13:21:26]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 12 milliseconds ago.  The last packet sent successfully to the server was 11 milliseconds ago.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
	at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:201)
	at com.mysql.jdbc.MysqlIO.negotiateSSLConnection(MysqlIO.java:4869)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1656)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1217)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2189)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor95.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:354)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:554)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:167)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:175)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:76)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470)
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384)
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488)
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:895)
	at java.lang.Thread.run(Unknown Source)
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
	at sun.security.ssl.Handshaker.process_record(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:186)
	... 43 more
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
	at com.mysql.jdbc.ExportControlled$X509TrustManagerWrapper.checkServerTrusted(ExportControlled.java:302)
	at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(Unknown Source)
	... 52 more
Caused by: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(Unknown Source)
	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(Unknown Source)
	at java.security.cert.CertPathValidator.validate(Unknown Source)
	at com.mysql.jdbc.ExportControlled$X509TrustManagerWrapper.checkServerTrusted(ExportControlled.java:295)
	... 53 more

[04-28 13:21:26]: [WARN] Aborting initialization of AuthMe: [IllegalStateException]: Error during initialization of data source
[04-28 13:21:26]: java.lang.IllegalStateException: Error during initialization of data source
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:52)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470)
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384)
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488)
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:895)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 12 milliseconds ago.  The last packet sent successfully to the server was 11 milliseconds ago.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
	at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:201)
	at com.mysql.jdbc.MysqlIO.negotiateSSLConnection(MysqlIO.java:4869)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1656)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1217)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2189)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor95.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:354)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:554)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:167)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:175)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:76)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	... 17 more
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
	at sun.security.ssl.Handshaker.process_record(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:186)
	... 43 more
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
	at com.mysql.jdbc.ExportControlled$X509TrustManagerWrapper.checkServerTrusted(ExportControlled.java:302)
	at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(Unknown Source)
	... 52 more
Caused by: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(Unknown Source)
	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(Unknown Source)
	at java.security.cert.CertPathValidator.validate(Unknown Source)
	at com.mysql.jdbc.ExportControlled$X509TrustManagerWrapper.checkServerTrusted(ExportControlled.java:295)
	... 53 more

[04-28 13:21:26]: [INFO] AuthMe 5.6.0-SNAPSHOT-b2388 disabled!
[04-28 13:24:19]: [INFO] Connection arguments loaded, Hikari ConnectionPool ready!
[04-28 13:24:20]: [INFO] Created column 'regdate' and set the current timestamp, 1588101860780, to all 0 rows
[04-28 13:24:21]: [INFO] MySQL setup finished
[04-28 13:24:21]: [INFO] Hooked into LuckPerms!
[04-28 13:24:21]: [INFO] Hooked successfully into Essentials
[04-28 13:24:21]: [INFO] Hooked successfully into Multiverse-Core
[04-28 13:24:21]: [INFO] AuthMe 5.6.0-SNAPSHOT build n.2388 successfully enabled!
[04-28 13:24:23]: [INFO] Downloading GEO IP database, because the old database is older than 30 days or doesn't exist
[04-28 13:24:23]: [WARN] No MaxMind credentials found in the configuration file! GeoIp protections will be disabled.
[04-28 13:24:23]: [INFO] There is no newer GEO IP database uploaded to MaxMind. Using the old one for now.
[04-28 13:24:23]: [WARN] Could not download GeoLiteAPI database [FileNotFoundException]: plugins\AuthMe\GeoLite2-Country.mmdb (系统找不到指定的文件。)
[04-28 13:24:23]: java.io.FileNotFoundException: plugins\AuthMe\GeoLite2-Country.mmdb (系统找不到指定的文件。)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(Unknown Source)
	at java.io.RandomAccessFile.<init>(Unknown Source)
	at fr.xephi.authme.libs.com.maxmind.db.BufferHolder.<init>(BufferHolder.java:20)
	at fr.xephi.authme.libs.com.maxmind.db.Reader.<init>(Reader.java:121)
	at fr.xephi.authme.service.GeoIpService.startReading(GeoIpService.java:173)
	at fr.xephi.authme.service.GeoIpService.updateDatabase(GeoIpService.java:144)
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[04-28 14:29:41]: [INFO] AuthMe 5.6.0-SNAPSHOT-b2388 disabled!
[04-28 14:30:48]: [INFO] Connection arguments loaded, Hikari ConnectionPool ready!
[04-28 14:30:48]: [INFO] MySQL setup finished
[04-28 14:30:48]: [INFO] Hooked into LuckPerms!
[04-28 14:30:49]: [INFO] Hooked successfully into Essentials
[04-28 14:30:49]: [INFO] Hooked successfully into Multiverse-Core
[04-28 14:30:49]: [INFO] AuthMe 5.6.0-SNAPSHOT build n.2388 successfully enabled!
[04-28 14:30:51]: [INFO] Downloading GEO IP database, because the old database is older than 30 days or doesn't exist
[04-28 14:30:51]: [WARN] No MaxMind credentials found in the configuration file! GeoIp protections will be disabled.
[04-28 14:30:51]: [INFO] There is no newer GEO IP database uploaded to MaxMind. Using the old one for now.
[04-28 14:30:51]: [WARN] Could not download GeoLiteAPI database [FileNotFoundException]: plugins\AuthMe\GeoLite2-Country.mmdb (系统找不到指定的文件。)
[04-28 14:30:51]: java.io.FileNotFoundException: plugins\AuthMe\GeoLite2-Country.mmdb (系统找不到指定的文件。)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(Unknown Source)
	at java.io.RandomAccessFile.<init>(Unknown Source)
	at fr.xephi.authme.libs.com.maxmind.db.BufferHolder.<init>(BufferHolder.java:20)
	at fr.xephi.authme.libs.com.maxmind.db.Reader.<init>(Reader.java:121)
	at fr.xephi.authme.service.GeoIpService.startReading(GeoIpService.java:173)
	at fr.xephi.authme.service.GeoIpService.updateDatabase(GeoIpService.java:144)
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[04-28 14:32:21]: [FINE] BiShop registered 127.0.0.1
[04-28 14:32:21]: [FINE] BiShop logged in!
[04-28 14:40:06]: [INFO] AuthMe 5.6.0-SNAPSHOT-b2388 disabled!
[04-28 14:41:47]: [INFO] Connection arguments loaded, Hikari ConnectionPool ready!
[04-28 14:41:47]: [INFO] MySQL setup finished
[04-28 14:41:48]: [INFO] Hooked into LuckPerms!
[04-28 14:41:48]: [INFO] Hooked successfully into Essentials
[04-28 14:41:48]: [INFO] Hooked successfully into Multiverse-Core
[04-28 14:41:48]: [INFO] AuthMe 5.6.0-SNAPSHOT build n.2388 successfully enabled!
[04-28 14:41:50]: [INFO] Downloading GEO IP database, because the old database is older than 30 days or doesn't exist
[04-28 14:41:50]: [WARN] No MaxMind credentials found in the configuration file! GeoIp protections will be disabled.
[04-28 14:41:50]: [INFO] There is no newer GEO IP database uploaded to MaxMind. Using the old one for now.
[04-28 14:41:50]: [WARN] Could not download GeoLiteAPI database [FileNotFoundException]: plugins\AuthMe\GeoLite2-Country.mmdb (系统找不到指定的文件。)
[04-28 14:41:50]: java.io.FileNotFoundException: plugins\AuthMe\GeoLite2-Country.mmdb (系统找不到指定的文件。)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(Unknown Source)
	at java.io.RandomAccessFile.<init>(Unknown Source)
	at fr.xephi.authme.libs.com.maxmind.db.BufferHolder.<init>(BufferHolder.java:20)
	at fr.xephi.authme.libs.com.maxmind.db.Reader.<init>(Reader.java:121)
	at fr.xephi.authme.service.GeoIpService.startReading(GeoIpService.java:173)
	at fr.xephi.authme.service.GeoIpService.updateDatabase(GeoIpService.java:144)
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[04-28 14:47:36]: [FINE] BiShop logged in!
[04-28 14:51:02]: [INFO] AuthMe 5.6.0-SNAPSHOT-b2388 disabled!
[04-28 14:52:43]: [INFO] Connection arguments loaded, Hikari ConnectionPool ready!
[04-28 14:52:43]: [INFO] MySQL setup finished
[04-28 14:52:43]: [INFO] Hooked into LuckPerms!
[04-28 14:52:43]: [INFO] Hooked successfully into Essentials
[04-28 14:52:43]: [INFO] Hooked successfully into Multiverse-Core
[04-28 14:52:44]: [INFO] AuthMe 5.6.0-SNAPSHOT build n.2388 successfully enabled!
[04-28 14:52:45]: [INFO] Downloading GEO IP database, because the old database is older than 30 days or doesn't exist
[04-28 14:52:45]: [WARN] No MaxMind credentials found in the configuration file! GeoIp protections will be disabled.
[04-28 14:52:45]: [INFO] There is no newer GEO IP database uploaded to MaxMind. Using the old one for now.
[04-28 14:52:45]: [WARN] Could not download GeoLiteAPI database [FileNotFoundException]: plugins\AuthMe\GeoLite2-Country.mmdb (系统找不到指定的文件。)
[04-28 14:52:45]: java.io.FileNotFoundException: plugins\AuthMe\GeoLite2-Country.mmdb (系统找不到指定的文件。)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(Unknown Source)
	at java.io.RandomAccessFile.<init>(Unknown Source)
	at fr.xephi.authme.libs.com.maxmind.db.BufferHolder.<init>(BufferHolder.java:20)
	at fr.xephi.authme.libs.com.maxmind.db.Reader.<init>(Reader.java:121)
	at fr.xephi.authme.service.GeoIpService.startReading(GeoIpService.java:173)
	at fr.xephi.authme.service.GeoIpService.updateDatabase(GeoIpService.java:144)
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[04-28 14:53:25]: [FINE] BiShop logged in!
